### ISSUE TITLE
Symbol not found using require

### ISSUE THREAD

**Issue by Kikobeats** [brave/tracking-protection#25]
Hello,

I'm trying to require the library from the NPM registry but something is failing:

```js
> const TrackingProtection = require('tracking-protection')
Error: dlopen(/Users/josefranciscoverdugambin/Projects/browserless/packages/browserless/node_modules/tracking-protection/build/Release/tp_node_addon.node, 1): Symbol not found: __ZTV6HashFn
  Referenced from: /Users/josefranciscoverdugambin/Projects/browserless/packages/browserless/node_modules/tracking-protection/build/Release/tp_node_addon.node
  Expected in: flat namespace
 in /Users/josefranciscoverdugambin/Projects/browserless/packages/browserless/node_modules/tracking-protection/build/Release/tp_node_addon.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

this is the [installation log](https://gist.github.com/Kikobeats/3929e2269b5e425c5541565e12acd869).

I tried using different node versions but without successfully. Any idea?

**Comment by SergeyZhukovsky** [comment]
Are you able to build the tracking protection lib itself? The `tp_node_addon.node` should be built to be able to use it from JS.

**Comment by Kikobeats** [comment]
Yes, I guess. I mean, it exists in the directory as output after run `postinstall` step:

```
❯ l build/Release
total 648
drwxr-xr-x  10 josefranciscoverdugambin  staff   320B Jan  2 22:00 .
drwxr-xr-x  12 josefranciscoverdugambin  staff   384B Jan  2 22:00 ..
drwxr-xr-x   3 josefranciscoverdugambin  staff    96B Jan  2 22:00 .deps
-rw-r--r--   1 josefranciscoverdugambin  staff    53K Jan  2 22:00 CppUnitLite.a
-rwxr-xr-x   1 josefranciscoverdugambin  staff    25K Jan  2 22:00 hashset-cpp.node
drwxr-xr-x   8 josefranciscoverdugambin  staff   256B Jan  2 22:00 obj.target
-rwxr-xr-x   1 josefranciscoverdugambin  staff    50K Jan  2 22:00 sample
-rwxr-xr-x   1 josefranciscoverdugambin  staff    49K Jan  2 22:00 test
-rwxr-xr-x   1 josefranciscoverdugambin  staff    42K Jan  2 22:00 tp_node_addon.node
-rw-r--r--   1 josefranciscoverdugambin  staff    89K Jan  2 22:00 tracking-protection.a
```

**Comment by SergeyZhukovsky** [comment]
You should require `tp_node_addon` instead of `tracking-protection`
https://github.com/brave/tracking-protection/blob/master/scripts/read_data.js#L6

**Comment by Kikobeats** [comment]
Yes, it's the same file declared as `main` https://github.com/brave/tracking-protection/blob/master/package.json#L5

Having the same error requering it directly:

```js
const path = require('path')

const requirePath = path.resolve(
  __dirname,
  'node_modules/tracking-protection/build/Release/tp_node_addon'
)

const trackingProtection = require(requirePath)

internal/modules/cjs/loader.js:750
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Users/josefranciscoverdugambin/Projects/browserless/packages/browserless/node_modules/tracking-protection/build/Release/tp_node_addon.node, 1): Symbol not found: __ZTV6HashFn
  Referenced from: /Users/josefranciscoverdugambin/Projects/browserless/packages/browserless/node_modules/tracking-protection/build/Release/tp_node_addon.node
  Expected in: flat namespace
 in /Users/josefranciscoverdugambin/Projects/browserless/packages/browserless/node_modules/tracking-protection/build/Release/tp_node_addon.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:750:18)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/josefranciscoverdugambin/Projects/browserless/packages/browserless/example.js:12:28)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
```

**Comment by karliky** [comment]
I'm facing the same issue. It also fails by requiring the .node lib:
```
> const Traking = require('/Users/mypc/node_modules/tracking-protection/build/Release/tp_node_addon.node')
Error: dlopen(/Users/mypc/node_modules/tracking-protection/build/Release/tp_node_addon.node, 1): Symbol not found: __ZTV6HashFn
  Referenced from: /Users/mypc/node_modules/tracking-protection/build/Release/tp_node_addon.node
  Expected in: flat namespace
 in /Users/mypc/node_modules/tracking-protection/build/Release/tp_node_addon.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
```

**Comment by karliky** [comment]
I suppose that `https://github.com/bbondy/bloom-filter-cpp/blob/master/hashFn.h` is not linked in the compile time. That's the symbol not found.
